before_script:
  - nvm use 14.0.0
  - node -v

stages:
  - clean
  - build_admin
  - build_server
  - build_main

clean1:
  stage: clean
  only:
    - dev
  script:
    - rm -rf /home/wwwroot/nav.geekape.net/
    - echo "清空nav.geekape.net目录成功"
    - pm2 stop all
    - pm2 delete all

#打包admin
build_admin:
  stage: build_admin
  only:
    - dev
  script:
    # 将镜像源设置成淘宝镜像
    - yarn config set registry 'https://registry.npm.taobao.org'
    - cd geekape-nav-admin
    - tyarn install
    - echo "admin安装完成1"
    - yarn build
    - echo "admin打包完成"
    - mv dist admin
    - mkdir /home/wwwroot/nav.geekape.net
    - mv admin/ /home/wwwroot/nav.geekape.net/
    - echo "admin移动目录完成"

#打包server
build_server:
  stage: build_server
  only:
    - dev
  script:
    - mv geekape-nav-server/ /home/wwwroot/nav.geekape.net/
    - echo "server移动目录完成"
    - cd /home/wwwroot/nav.geekape.net/
    - mv geekape-nav-server server
    - cd server/
    - tyarn install
    - echo "server包安装完成"
    - pm2 start npm --name "geekape-nav-server" -- run server
    - echo "pm2 server启动成功"

#打包main
build_main:
  stage: build_main
  only:
    - dev
  script:
    # 将镜像源设置成淘宝镜像
    - yarn config set registry 'https://registry.npm.taobao.org'
    - cd geekape-nav-main
    - tyarn install
    - echo "main安装完成"
    - yarn build
    - echo "main打包完成"
    - mv .nuxt/ static/ package.json nuxt.config.js /home/wwwroot/nav.geekape.net/
    - cd /home/wwwroot/nav.geekape.net/
    - tyarn install
    - echo "main包安装完成，可以运行"
    - pm2 start npm --name "geekape-nav-main" -- run server
    - echo "pm2 main启动成功"
    

    